

<div id="ecom-header" class="header">
    <div class="panel wrapper topbar d-none d-md-block">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-md-6 cms-header-links">
                    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('header-links')->toHtml();?>
                </div>
                <div class="col-lg-7 col-md-6 header-top-links">
                    <?php echo $this->getChildHtml('header_links') ?>
                    <?php echo $this->getChildHtml('store_language') ?>
                    <?php echo $this->getChildHtml('currency') ?>
                </div>
            </div>
        </div>
    </div>

    <!-- header content -->
    <div class="header-content">
        <div class="container">
            <div class="row">
                <div class="col-lg-2 col-md-3">
                    <div class="logo-wrapper">
                        <?php echo $this->getChildHtml('logo') ?>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6">
                    <div class="search-wrapper">
                        <?php echo $this->getChildHtml('topSearch') ?>
                    </div>
                    <div class="advanced-search d-none d-md-block">
                        <a href="<?php echo $this->getUrl('catalogsearch/advanced/');?>" title="Advanced Search"><span class="fa fa-cogs" aria-hidden="true">&nbsp;</span></a>
                    </div>
                </div>
                <div class="col-lg-4 col-md-3">
                    <div class="pull-left d-none d-lg-block">
                        <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('call-us')->toHtml();?>
                    </div>
                    <?php echo $this->getChildHtml('minicart') ?>
                </div>
            </div>
        </div>
    </div>
</div>
